In [2]:
# Import libraries
import pandas as pd
import numpy as np
import scipy.stats as st
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv("imdb.csv")
data.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [5]:
# Pick some variables
df = data[["IMDB_Rating", "Released_Year", "Runtime", 
           "Meta_score", "Gross", "Director"]]
df.head()

,IMDB_Rating,Released_Year,Runtime,Meta_score,Gross,Director
0,9.3,1994,142 min,80.0,"28,341,469",Frank Darabont
1,9.2,1972,175 min,100.0,"134,966,411",Francis Ford Coppola
2,9.0,2008,152 min,84.0,"534,858,444",Christopher Nolan
3,9.0,1974,202 min,90.0,"57,300,000",Francis Ford Coppola
4,9.0,1957,96 min,96.0,"4,360,000",Sidney Lumet

In [6]:
# Look at df
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   IMDB_Rating    1000 non-null   float64
 1   Released_Year  1000 non-null   str
 2   Runtime        1000 non-null   str
 3   Meta_score     843 non-null    float64
 4   Gross          831 non-null    str
 5   Director       1000 non-null   str
dtypes: float64(2), str(4)
memory usage: 47.0 KB

In [8]:
# Convert Released_Year to numeric
df['Released_Year'] = pd.to_numeric(df['Released_Year'],
                                   errors = "coerce")

In [9]:
# Check Row 966
df.iloc[966]

IMDB_Rating              7.6
Released_Year            NaN
Runtime              140 min
Meta_score              77.0
Gross            173,837,933
Director          Ron Howard
Name: 966, dtype: object

In [12]:
# Create a decade variable
df['Decade'] = np.floor(df['Released_Year'] / 10) * 10

In [17]:
# Convert and transform Runtime
df['Runtime'] = df['Runtime'].str.replace("min", "").astype(int)

In [18]:
# Fill the NaN values with zero
df['Gross'] = df['Gross'].fillna(0)
print(df['Gross'].isna().sum())

0

In [20]:
# Convert and transform the Gross Variable
df['Gross'] = df['Gross'].str.replace(",", "").fillna(0).astype(int)

In [22]:
df['Gross_mil'] = df['Gross'] / 1000000

In [24]:
# Finalize this df
df = df.drop(columns = ['Released_Year', 'Gross'])
df.head()

   IMDB_Rating  Runtime  Meta_score              Director  Decade   Gross_mil
0          9.3      142        80.0        Frank Darabont  1990.0   28.341469
1          9.2      175       100.0  Francis Ford Coppola  1970.0  134.966411
2          9.0      152        84.0     Christopher Nolan  2000.0  534.858444
3          9.0      202        90.0  Francis Ford Coppola  1970.0   57.300000
4          9.0       96        96.0          Sidney Lumet  1950.0    4.360000